services:
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    environment:
      - NEXTAUTH_URL=https://bot.wsagency-dz.com
      - NEXT_PUBLIC_VIEWER_URL=https://nextcloud.wsagency-dz.com
      - NEXT_PUBLIC_BUILDER_URL=https://bot.wsagency-dz.com
    ports:
      - "8082:3000"
    networks:
      - typebot-network

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    environment:
      - NEXT_PUBLIC_VIEWER_URL=https://nextcloud.wsagency-dz.com
    ports:
      - "8081:3000"
    networks:
      - typebot-network

networks:
  typebot-network:
    driver: bridge
