# nixpacks.toml

[phases.setup]
# Install system dependencies for node-gyp
aptPkgs = ['build-essential', 'python3']
# Explicitly install node-gyp globally to make it available in the PATH
cmds = ['npm install -g node-gyp']

[start]
# Command to start the application
cmd = 'pnpm start'
